const currencies={
BRL:{country:'Brasil',flag:'\u{1F1E7}\u{1F1F7}',image:'flag1.png',name:'Real',capital:'Bras\u00edlia',region:'Am\u00e9rica do Sul',symbol:'R$',perBRL:1,color:'#e0f9e8'},
MXN:{country:'M\u00e9xico',flag:'\u{1F1F2}\u{1F1FD}',image:'flag2.png',name:'Peso mexicano',capital:'Cidade do M\u00e9xico',region:'Am\u00e9rica do Norte',symbol:'$',perBRL:3.5,color:'#ffe2ec'},
ARS:{country:'Argentina',flag:'\u{1F1E6}\u{1F1F7}',image:'flag3.png',name:'Peso argentino',capital:'Buenos Aires',region:'Am\u00e9rica do Sul',symbol:'$',perBRL:200,color:'#e9dfff'},
USD:{country:'Estados Unidos',flag:'\u{1F1FA}\u{1F1F8}',image:'flag4.png',name:'D\u00f3lar americano',capital:'Washington, D.C.',region:'Am\u00e9rica do Norte',symbol:'US$',perBRL:.2,color:'#dfefff'},
CAD:{country:'Canad\u00e1',flag:'\u{1F1E8}\u{1F1E6}',image:'flag5.png',name:'D\u00f3lar canadense',capital:'Ottawa',region:'Am\u00e9rica do Norte',symbol:'C$',perBRL:.27,color:'#fff0d2'},
CLP:{country:'Chile',flag:'\u{1F1E8}\u{1F1F1}',image:'flag6.png',name:'Peso chileno',capital:'Santiago',region:'Am\u00e9rica do Sul',symbol:'$',perBRL:180,color:'#ffe0e9'},
EGP:{country:'Egito',flag:'\u{1F1EA}\u{1F1EC}',image:'egito.png',name:'Libra eg\u00edpcia',capital:'Cairo',region:'\u00c1frica',symbol:'E£',perBRL:9,color:'#fff0d2'},
JPY:{country:'Jap\u00e3o',flag:'\u{1F1EF}\u{1F1F5}',image:'japan.png',name:'Iene japon\u00eas',capital:'T\u00f3quio',region:'\u00c1sia',symbol:'¥',perBRL:30,color:'#e9dfff'},
EUR:{country:'Fran\u00e7a',flag:'\u{1F1EB}\u{1F1F7}',image:'france.png',name:'Euro',capital:'Paris',region:'Europa',symbol:'€',perBRL:.16,color:'#dfefff'},
AUD:{country:'Austr\u00e1lia',flag:'\u{1F1E6}\u{1F1FA}',image:'australia.png',name:'D\u00f3lar australiano',capital:'Canberra',region:'Oceania',symbol:'A$',perBRL:.27,color:'#e0f9e8'},
GBP:{country:'Reino Unido',flag:'\u{1F1EC}\u{1F1E7}',image:'reino.png',name:'Libra esterlina',capital:'Londres',region:'Europa',symbol:'£',perBRL:.14,color:'#e6e0ff'},
ANT:{country:'Ant\u00e1rtida',flag:'\u{1F1E6}\u{1F1F6}',name:'N\u00e3o possui moeda oficial',capital:'N\u00e3o possui capital',region:'Ant\u00e1rtida',symbol:'—',color:'#e6f6ff',convertible:false}};
const amount=document.querySelector('#amount'),from=document.querySelector('#from'),to=document.querySelector('#to'),coin='&#x1FA99;';let usingLiveRates=false;
const fmt=n=>n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function options(select,chosen){select.innerHTML=Object.entries(currencies).filter(([,c])=>c.convertible!==false).map(([code,c])=>`<option value="${code}" ${code===chosen?'selected':''}>${c.country} &middot; ${code}</option>`).join('')}
function updateSelectFlag(select){const currency=currencies[select.value],box=select.parentElement;let flag=box.querySelector('.selected-currency-flag');if(!flag){flag=document.createElement('img');flag.className='selected-currency-flag';box.insertBefore(flag,select)}flag.src=currency.image;flag.alt=`Bandeira do ${currency.country}`}
function updateQuote(origin,dest,originCode,destCode,unitRate){let card=document.querySelector('#quote-card');if(!card){card=document.createElement('section');card.id='quote-card';card.className='quote-card';card.innerHTML='<span class="quote-icon">⇆</span><div><small>Cotação utilizada</small><strong id="quote-primary"></strong><p id="quote-secondary"></p></div><b id="quote-badge"></b>';document.querySelector('.convert-button').before(card)}document.querySelector('#quote-primary').innerHTML=`${dest.symbol} 1,00 <span class="quote-curr-name">${dest.name}</span> = ${origin.symbol} ${fmt(1/unitRate)} <span class="quote-curr-name">${origin.name}</span>`;document.querySelector('#quote-secondary').innerHTML=`${origin.symbol} 1,00 <span class="quote-curr-name">${origin.name}</span> = ${dest.symbol} ${fmt(unitRate)} <span class="quote-curr-name">${dest.name}</span>`;document.querySelector('#quote-badge').textContent=usingLiveRates?'Cotação do dia':'Taxa fictícia';card.setAttribute('aria-label',`Cotação: 1 ${dest.name} equivale a ${fmt(1/unitRate)} ${origin.name}`)}
function convert(){const origin=currencies[from.value],dest=currencies[to.value],input=Math.max(0,Number(amount.value)||0),value=input/origin.perBRL*dest.perBRL,unitRate=dest.perBRL/origin.perBRL;updateSelectFlag(from);updateSelectFlag(to);updateQuote(origin,dest,from.value,to.value,unitRate);document.querySelector('#input-symbol').textContent=origin.symbol;document.querySelector('#converted').innerHTML=`${fmt(value)} <small>${to.value}</small> <span class="dest-currency-badge">${dest.name}</span>`;document.querySelector('#equation').innerHTML=`<b>${fmt(input)} ${origin.name} (${from.value})</b> = <b>${fmt(value)} ${dest.name} (${to.value})</b>`;let dailyRate=document.querySelector('#daily-rate');if(!dailyRate){dailyRate=document.createElement('p');dailyRate.id='daily-rate';dailyRate.className='daily-rate';document.querySelector('#equation').after(dailyRate)}dailyRate.textContent=usingLiveRates?'Conversão calculada com a cotação do dia.':'Valores ilustrativos para fins escolares.';miniCards();}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector(`#${page}-page`).classList.add('active');document.querySelectorAll('.menu button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
function flagMarkup(c,className){return c.image?`<img class="${className}" src="${c.image}" alt="Bandeira do ${c.country}">`:`<span class="${className}-emoji">${c.flag}</span>`}
function countryGrid(){document.querySelector('#country-grid').innerHTML=Object.entries(currencies).map(([code,c])=>`<article class="country-card" data-region="${c.region}" style="--card:${c.color}"><div class="card-flag">${flagMarkup(c,'country-flag-image')}<span class="card-coin">${c.convertible===false?'🧊':coin}</span></div><h2>${c.country}</h2><p class="region">${c.region}</p><p>${coin} &nbsp; Moeda: <b>${c.name}</b><code>${c.convertible===false?'—':code}</code></p><p>&#x1F4CD; &nbsp; Capital: <b>${c.capital}</b></p>${c.convertible===false?'<button type="button" disabled>Sem moeda oficial</button>':`<button data-convert="${code}">Converter &nbsp; &#10140;</button>`}</article>`).join('')}
function miniCards(){const origin=currencies[from.value]||currencies['BRL'],destCode=to.value,input=Math.max(0,Number(amount.value)||0);const titleEl=document.querySelector('#mini-title'),descEl=document.querySelector('#mini-desc');if(titleEl)titleEl.innerHTML=`${origin.country} &times; outros pa&iacute;ses`;if(descEl)descEl.textContent=`Conversão automática de ${origin.symbol} ${fmt(input)} (${from.value}) para as demais moedas:`;const miniList=document.querySelector('#mini-list');if(!miniList)return;miniList.innerHTML=Object.entries(currencies).filter(([code,c])=>code!==from.value&&c.convertible!==false).map(([code,c])=>{const convertedVal=(input/origin.perBRL)*c.perBRL;const isSelected=code===destCode;return `<article class="mini ${isSelected?'mini-active-target':''}" style="--card:${c.color}" onclick="selectDestinationCurrency('${code}')" title="Clique para definir ${c.name} como moeda de destino">${isSelected?'<span class="mini-target-badge">🎯 Moeda Selecionada</span>':''}<h3>${origin.country} &times; ${c.country}</h3><div class="mini-info">${c.image?flagMarkup(c,'mini-flag-image'):`<span class="mini-flag-emoji">${c.flag}</span>`}<span class="mini-currency">${c.name} &middot; ${code}</span></div><strong>${coin} ${fmt(convertedVal)} ${code}</strong></article>`}).join('')}
function selectDestinationCurrency(code){if(currencies[code]&&currencies[code].convertible!==false&&code!==from.value){to.value=code;convert();}}
function swapCurrencies(){const button=document.querySelector('.swap');[from.value,to.value]=[to.value,from.value];button.classList.remove('is-swapping');void button.offsetWidth;button.classList.add('is-swapping');convert()}
async function loadLiveRates(){try{const response=await fetch('/.netlify/functions/rates?base=BRL');if(!response.ok)throw new Error();const payload=await response.json();Object.entries(payload.rates).forEach(([code,rate])=>{if(currencies[code]&&currencies[code].convertible!==false&&typeof rate==='number')currencies[code].perBRL=rate});usingLiveRates=true;convert();miniCards();countryGrid();bindCountryButtons();}catch{ /* Mantem as taxas educativas quando a Function nao estiver configurada. */ }}
function bindCountryButtons(){document.querySelectorAll('[data-convert]').forEach(button=>button.addEventListener('click',()=>{from.value='BRL';to.value=button.dataset.convert;convert();go('home')}))}
options(from,'BRL');options(to,'BRL');countryGrid();miniCards();convert();bindCountryButtons();
[amount,from,to].forEach(x=>{x.addEventListener('input',convert);x.addEventListener('change',convert)});document.querySelector('.convert-button').addEventListener('click',convert);document.querySelector('.swap').addEventListener('click',swapCurrencies);document.querySelector('.swap').addEventListener('animationend',event=>event.currentTarget.classList.remove('is-swapping'));document.querySelectorAll('.menu button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));document.querySelector('[data-go-converter]').addEventListener('click',()=>go('home'));document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');const region=button.dataset.region;document.querySelectorAll('.country-card').forEach(card=>{card.style.display=!region||card.dataset.region===region?'block':'none'})}));loadLiveRates();

function testCurrency(code){if(currencies[code]&&currencies[code].convertible!==false){from.value='BRL';to.value=code;amount.value=100;convert();go('home');const resultBox=document.querySelector('.result');if(resultBox){resultBox.scrollIntoView({behavior:'smooth',block:'center'});resultBox.style.transition='transform 0.3s ease, box-shadow 0.3s ease';resultBox.style.transform='scale(1.03)';resultBox.style.boxShadow='0 0 25px rgba(116,69,213,0.4)';setTimeout(()=>{resultBox.style.transform='none';resultBox.style.boxShadow='';},800)}}}

function applaudStudent(id,button){const countEl=document.querySelector(`#count-${id}`);if(countEl){let current=parseInt(countEl.textContent,10)||0;countEl.textContent=current+1;}if(button){button.classList.add('is-applauding');setTimeout(()=>button.classList.remove('is-applauding'),350);const emojis=['👏','⭐','🪙','🎉','💖','✨'];for(let i=0;i<5;i++){const p=document.createElement('span');p.className='applause-particle';p.textContent=emojis[Math.floor(Math.random()*emojis.length)];const rect=button.getBoundingClientRect();const x=rect.left+rect.width/2+(Math.random()*50-25);const y=rect.top+window.scrollY+(Math.random()*20-10);p.style.left=`${x}px`;p.style.top=`${y}px`;document.body.appendChild(p);setTimeout(()=>p.remove(),950);}}}

window.go=go;window.testCurrency=testCurrency;window.applaudStudent=applaudStudent;
go('start');
